//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.10 at 01:40:55 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://models", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package models;
